import React from "react";
import { useTable, usePagination, useSortBy, useFilters } from "react-table";
import Pagination from "../pagination";
import DefaultColumnFilter from "./ColumnFilter";
import { useAppUsersColumns } from "./columns";
import TableCell from "./TableCell";
import TableHeadCell from "./TableHeadCell";
import { AppUser } from "../../../types";
import Table from "./Table";

const DATA: AppUser[] = [
  {
    name: "Falakhe",
    surname: "sivela",
    contact: "+27651234546",
    selected_doctor: "Dr. The good doctor",
    sp_uses: 3,
    ahdx_uses: 10,
    active_profiles: 2 / 4,
    profile_status: "limit reached",
    client: "bidvest",
    id: "1",
  },
  {
    name: "Falakhe",
    surname: "langa",
    contact: "+27651234546",
    selected_doctor: "Dr. The good doctor",
    sp_uses: 3,
    ahdx_uses: 10,
    active_profiles: 2 / 4,
    profile_status: "active",
    client: "bidvest",
    id: "2",
  },
  {
    name: "Falakhe",
    surname: "sivela",
    contact: "+27651234546",
    selected_doctor: "Dr. The good doctor",
    sp_uses: 3,
    ahdx_uses: 10,
    active_profiles: 2 / 4,
    profile_status: "active",
    client: "bidvest",
    id: "3",
  },
  {
    name: "Falakhe",
    surname: "sivela",
    contact: "+27651234546",
    selected_doctor: "Dr. The good doctor",
    sp_uses: 3,
    ahdx_uses: 10,
    active_profiles: 2 / 4,
    profile_status: "archived",
    client: "bidvest",
    id: "4",
  },
  {
    name: "Falakhe",
    surname: "sivela",
    contact: "+27651234546",
    selected_doctor: "Dr. The good doctor",
    sp_uses: 3,
    ahdx_uses: 10,
    active_profiles: 2 / 4,
    profile_status: "deactivated",
    client: "bidvest",
    id: "5",
  },
  {
    name: "Falakhe",
    surname: "sivela",
    contact: "+27651234546",
    selected_doctor: "Dr. The good doctor",
    sp_uses: 3,
    ahdx_uses: 10,
    active_profiles: 2 / 4,
    profile_status: "deactivated",
    client: "bidvest",
    id: "5",
  },
  {
    name: "Falakhe",
    surname: "sivela",
    contact: "+27651234546",
    selected_doctor: "Dr. The good doctor",
    sp_uses: 3,
    ahdx_uses: 10,
    active_profiles: 2 / 4,
    profile_status: "deactivated",
    client: "bidvest",
    id: "5",
  },
  {
    name: "Falakhe",
    surname: "sivela",
    contact: "+27651234546",
    selected_doctor: "Dr. The good doctor",
    sp_uses: 3,
    ahdx_uses: 10,
    active_profiles: 2 / 4,
    profile_status: "deactivated",
    client: "bidvest",
    id: "5",
  },
  {
    name: "Falakhe",
    surname: "sivela",
    contact: "+27651234546",
    selected_doctor: "Dr. The good doctor",
    sp_uses: 3,
    ahdx_uses: 10,
    active_profiles: 2 / 4,
    profile_status: "deactivated",
    client: "bidvest",
    id: "5",
  },
  {
    name: "Falakhe",
    surname: "sivela",
    contact: "+27651234546",
    selected_doctor: "Dr. The good doctor",
    sp_uses: 3,
    ahdx_uses: 10,
    active_profiles: 2 / 4,
    profile_status: "deactivated",
    client: "bidvest",
    id: "5",
  },
  {
    name: "Falakhe",
    surname: "sivela",
    contact: "+27651234546",
    selected_doctor: "Dr. The good doctor",
    sp_uses: 3,
    ahdx_uses: 10,
    active_profiles: 2 / 4,
    profile_status: "deactivated",
    client: "bidvest",
    id: "5",
  },
  {
    name: "Falakhe",
    surname: "sivela",
    contact: "+27651234546",
    selected_doctor: "Dr. The good doctor",
    sp_uses: 3,
    ahdx_uses: 10,
    active_profiles: 2 / 4,
    profile_status: "deactivated",
    client: "bidvest",
    id: "5",
  },
  {
    name: "Falakhe",
    surname: "sivela",
    contact: "+27651234546",
    selected_doctor: "Dr. The good doctor",
    sp_uses: 3,
    ahdx_uses: 10,
    active_profiles: 2 / 4,
    profile_status: "deactivated",
    client: "bidvest",
    id: "5",
  },
  {
    name: "Falakhe",
    surname: "sivela",
    contact: "+27651234546",
    selected_doctor: "Dr. The good doctor",
    sp_uses: 3,
    ahdx_uses: 10,
    active_profiles: 2 / 4,
    profile_status: "deactivated",
    client: "bidvest",
    id: "5",
  },
  {
    name: "Falakhe",
    surname: "sivela",
    contact: "+27651234546",
    selected_doctor: "Dr. The good doctor",
    sp_uses: 3,
    ahdx_uses: 10,
    active_profiles: 2 / 4,
    profile_status: "deactivated",
    client: "bidvest",
    id: "5",
  },
  {
    name: "Falakhe",
    surname: "sivela",
    contact: "+27651234546",
    selected_doctor: "Dr. The good doctor",
    sp_uses: 3,
    ahdx_uses: 10,
    active_profiles: 2 / 4,
    profile_status: "deactivated",
    client: "bidvest",
    id: "5",
  },
  {
    name: "Falakhe",
    surname: "sivela",
    contact: "+27651234546",
    selected_doctor: "Dr. The good doctor",
    sp_uses: 3,
    ahdx_uses: 10,
    active_profiles: 2 / 4,
    profile_status: "deactivated",
    client: "bidvest",
    id: "5",
  },
  {
    name: "Falakhe",
    surname: "sivela",
    contact: "+27651234546",
    selected_doctor: "Dr. The good doctor",
    sp_uses: 3,
    ahdx_uses: 10,
    active_profiles: 2 / 4,
    profile_status: "deactivated",
    client: "bidvest",
    id: "5",
  },
  {
    name: "Falakhe",
    surname: "sivela",
    contact: "+27651234546",
    selected_doctor: "Dr. The good doctor",
    sp_uses: 3,
    ahdx_uses: 10,
    active_profiles: 2 / 4,
    profile_status: "deactivated",
    client: "bidvest",
    id: "5",
  },
  {
    name: "Falakhe",
    surname: "sivela",
    contact: "+27651234546",
    selected_doctor: "Dr. The good doctor",
    sp_uses: 3,
    ahdx_uses: 10,
    active_profiles: 2 / 4,
    profile_status: "deactivated",
    client: "bidvest",
    id: "5",
  },
  {
    name: "Falakhe",
    surname: "sivela",
    contact: "+27651234546",
    selected_doctor: "Dr. The good doctor",
    sp_uses: 3,
    ahdx_uses: 10,
    active_profiles: 2 / 4,
    profile_status: "deactivated",
    client: "bidvest",
    id: "5",
  },
  {
    name: "Falakhe",
    surname: "sivela",
    contact: "+27651234546",
    selected_doctor: "Dr. The good doctor",
    sp_uses: 3,
    ahdx_uses: 10,
    active_profiles: 2 / 4,
    profile_status: "deactivated",
    client: "bidvest",
    id: "5",
  },
  {
    name: "Falakhe",
    surname: "sivela",
    contact: "+27651234546",
    selected_doctor: "Dr. The good doctor",
    sp_uses: 3,
    ahdx_uses: 10,
    active_profiles: 2 / 4,
    profile_status: "deactivated",
    client: "bidvest",
    id: "5",
  },
  {
    name: "Falakhe",
    surname: "sivela",
    contact: "+27651234546",
    selected_doctor: "Dr. The good doctor",
    sp_uses: 3,
    ahdx_uses: 10,
    active_profiles: 2 / 4,
    profile_status: "deactivated",
    client: "bidvest",
    id: "5",
  },
  {
    name: "Falakhe",
    surname: "sivela",
    contact: "+27651234546",
    selected_doctor: "Dr. The good doctor",
    sp_uses: 3,
    ahdx_uses: 10,
    active_profiles: 2 / 4,
    profile_status: "deactivated",
    client: "bidvest",
    id: "5",
  },
  {
    name: "Falakhe",
    surname: "sivela",
    contact: "+27651234546",
    selected_doctor: "Dr. The good doctor",
    sp_uses: 3,
    ahdx_uses: 10,
    active_profiles: 2 / 4,
    profile_status: "deactivated",
    client: "bidvest",
    id: "5",
  },
  {
    name: "Falakhe",
    surname: "sivela",
    contact: "+27651234546",
    selected_doctor: "Dr. The good doctor",
    sp_uses: 3,
    ahdx_uses: 10,
    active_profiles: 2 / 4,
    profile_status: "deactivated",
    client: "bidvest",
    id: "5",
  },
  {
    name: "Falakhe",
    surname: "sivela",
    contact: "+27651234546",
    selected_doctor: "Dr. The good doctor",
    sp_uses: 3,
    ahdx_uses: 10,
    active_profiles: 2 / 4,
    profile_status: "deactivated",
    client: "bidvest",
    id: "5",
  },
  {
    name: "Falakhe",
    surname: "sivela",
    contact: "+27651234546",
    selected_doctor: "Dr. The good doctor",
    sp_uses: 3,
    ahdx_uses: 10,
    active_profiles: 2 / 4,
    profile_status: "deactivated",
    client: "bidvest",
    id: "5",
  },
  {
    name: "Falakhe",
    surname: "sivela",
    contact: "+27651234546",
    selected_doctor: "Dr. The good doctor",
    sp_uses: 3,
    ahdx_uses: 10,
    active_profiles: 2 / 4,
    profile_status: "deactivated",
    client: "bidvest",
    id: "5",
  },
  {
    name: "Falakhe",
    surname: "sivela",
    contact: "+27651234546",
    selected_doctor: "Dr. The good doctor",
    sp_uses: 3,
    ahdx_uses: 10,
    active_profiles: 2 / 4,
    profile_status: "deactivated",
    client: "bidvest",
    id: "5",
  },
  {
    name: "Falakhe",
    surname: "sivela",
    contact: "+27651234546",
    selected_doctor: "Dr. The good doctor",
    sp_uses: 3,
    ahdx_uses: 10,
    active_profiles: 2 / 4,
    profile_status: "deactivated",
    client: "bidvest",
    id: "5",
  },
  {
    name: "Falakhe",
    surname: "sivela",
    contact: "+27651234546",
    selected_doctor: "Dr. The good doctor",
    sp_uses: 3,
    ahdx_uses: 10,
    active_profiles: 2 / 4,
    profile_status: "deactivated",
    client: "bidvest",
    id: "5",
  },
  {
    name: "Falakhe",
    surname: "sivela",
    contact: "+27651234546",
    selected_doctor: "Dr. The good doctor",
    sp_uses: 3,
    ahdx_uses: 10,
    active_profiles: 2 / 4,
    profile_status: "deactivated",
    client: "bidvest",
    id: "5",
  },
  {
    name: "Falakhe",
    surname: "sivela",
    contact: "+27651234546",
    selected_doctor: "Dr. The good doctor",
    sp_uses: 3,
    ahdx_uses: 10,
    active_profiles: 2 / 4,
    profile_status: "deactivated",
    client: "bidvest",
    id: "5",
  },
];

const AppUsers = () => {
  const defaultColumn = React.useMemo(
    () => ({
      Filter: DefaultColumnFilter,
    }),
    []
  );
  const { columns } = useAppUsersColumns();
  const { getTableProps, getTableBodyProps, headerGroups, rows, prepareRow } =
    useTable(
      {
        columns,
        data: DATA,
        defaultColumn,
      },
      useFilters
    );
  return (
    <div className="w-full ">
      <Table
        rows={rows}
        getTableBodyProps={getTableBodyProps}
        headerGroups={headerGroups}
        getTableProps={getTableProps}
        prepareRow={prepareRow}
      />
    </div>
  );
};

export default AppUsers;
